In [1]:
print('mani')

mani


In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
array_one=np.array([1,2,3,4,5])
array_one

array([1, 2, 3, 4, 5])

In [6]:
type(array_one)

numpy.ndarray

In [8]:
array_of_events=np.arange(2,30,2)
array_of_events

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
array_of_events=np.arange(3,30,!2)
array_of_events

SyntaxError: invalid syntax (<ipython-input-9-b18144438af7>, line 1)

In [10]:
array_of_events=np.arange(3,30,2)
array_of_events

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [15]:
array_eye=np.eye(0)
array_eye

array([], shape=(0, 0), dtype=float64)

In [17]:
array_mani=np.arange(0,20)
array_mani

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [21]:
x=np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
x.shape

(8,)

In [23]:
array_nd=x.reshape(2,4)
array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
array_nd.shape

(2, 4)